services:
  - type: web
    name: ai-diagnosis-backend
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
          cd frontend && npm ci && npm run build && cd ..
          # ensure backend/static exists and copy build
          mkdir -p static
          cp -r frontend/dist/* static/ || true
        else
          echo "npm not found; skipping frontend build"
        fi
      fi
      # Install python deps
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
